version: '3.7'

services:

  postgres:
    image: postgres:11.6
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:Z
    env_file:
      - './rails_app/.env'
    ports:
      - "5432:5432"

  redis:
    image: 'redis:latest'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/var/lib/redis/data
    env_file:
      - './rails_app/.env'
    dns:
      - 8.8.8.8
  

volumes:
  redis:
  postgres: